[tool.poetry]
name = "mnemosyne-experimental"
version = "0.1.0"
description = "This is a personal experimental fork of the Mnemosyne Project for feature tests and contributions to the project repository."
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "mnemosyne_experimental"}]

[tool.poetry.dependencies]
python = "^3.8"
argon2-cffi = "^21.3.0"
cheroot = "^10.0.0"
cherrypy = "^18.8.0"
matplotlib = "^3.7.2"
webob = "^1.8.7"
sphinx = "^7.0.1"
pyqt6 = "^6.5.1"
pyqt6-webengine = "^6.5.0"
nose = "^1.3.7"
decorator = "^5.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
